FROM malirod/dev-cpputils

ENV HOME /root
ENV PROJECT_ROOT $HOME/project
ENV BOOST_BIN $HOME/libs/boost-bin
ENV BOOST_BRANCH boost-1.62-ubuntu-16.04-x64-clang-5.0-release-c++11-static-multi
ENV BOOST_HOME $BOOST_BIN/build

ADD . $PROJECT_ROOT

WORKDIR $PROJECT_ROOT
