FROM ubuntu:18.04

ENV HOME /root

WORKDIR $HOME

RUN apt update
RUN apt install -y wget
RUN apt install -y git
RUN apt install -y g++
RUN apt install -y make
RUN apt install -y ccache
RUN apt install -y libz-dev
RUN apt install -y libncurses-dev
RUN apt install -y libcurl4-openssl-dev
RUN apt install -y re2c
RUN apt install -y cmake
RUN apt install -y gnupg

# Install Clang-7

RUN echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main" | tee -a /etc/apt/sources.list
RUN echo "deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main" | tee -a /etc/apt/sources.list
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|apt-key add -
RUN apt update
RUN apt install -y clang-7 lldb-7 clang-format-7 clang-tidy-7 python-lldb-7
RUN update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-7 70
RUN update-alternatives --install /usr/bin/clang clang /usr/bin/clang-7 70
RUN update-alternatives --install /usr/bin/llvm-symbolizer llvm-symbolizer /usr/bin/llvm-symbolizer-7 70
RUN update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-7 70
RUN update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-7 70

# Install Conan
RUN apt install -y python-pip
RUN pip install conan
RUN conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

RUN apt install -y mc
RUN ldconfig
