FROM malirod/cpp-dev-base

ENV HOME /root
ENV PROJECT_ROOT $HOME/project

ADD . $PROJECT_ROOT

WORKDIR $PROJECT_ROOT

RUN conan config install ./tools/conan/cfg

# Pre-build all dependencies and cache them (they are release so just debug build with different compilers is sufficient)
RUN CXX=g++-8 CC=gcc-8 cmake -H. -Bbuild-gcc-debug -DCMAKE_BUILD_TYPE=Debug
RUN CXX=clang++-7 CC=clang-7 cmake -H. -Bbuild-clang-debug -DCMAKE_BUILD_TYPE=Debug

# Clean up all possible build dirs
RUN find . -maxdepth 1 -name "build*" -type d -exec rm -r {} +