FROM malirod/cpp-dev-base

ENV HOME /root
ENV PROJECT_ROOT $HOME/project
ENV PATH $NINJA_ROOT:$PATH

ADD . $PROJECT_ROOT

WORKDIR $PROJECT_ROOT

# Setup dependencies
RUN tools/conan/build.py

RUN mkdir build-clang-debug
RUN mkdir build-clang-release
RUN mkdir build-gcc-debug
RUN mkdir build-gcc-release
