FROM malirod/cpp-dev-base

ENV HOME /root
ENV PROJECT_ROOT $HOME/project

ADD . $PROJECT_ROOT

WORKDIR $PROJECT_ROOT

RUN mkdir build-clang-debug
RUN cd build-clang-debug && conan install .. --profile ../tools/conan/profile-clang --build missing && cd ..

RUN mkdir build-clang-release

RUN mkdir build-gcc-debug
RUN cd build-gcc-debug && conan install .. --profile ../tools/conan/profile-gcc --build missing && cd ..

RUN mkdir build-gcc-release
